/**
 * @file CelestialData.js
 * Comprehensive database of real astronomical objects spanning five scale tiers,
 * from planets and moons to the observable universe.
 *
 * Each object stores raw physical parameters; derived values (habitability
 * score, travel-time breakdowns) are computed on demand by the physics
 * engines so the data and the scoring logic never drift out of sync.
 *
 * @typedef {object} CelestialBody
 * @property {string} id - unique, lowercase, hyphen-free key.
 * @property {string} name - display name.
 * @property {'star'|'planet'|'dwarfPlanet'|'moon'|'asteroidBelt'|'blackHole'|'nebula'|'galaxy'|'structure'} type
 * @property {0|1|2|3|4} scaleTier - 0 Planetary, 1 Solar System, 2 Stellar, 3 Galactic, 4 Extragalactic.
 * @property {string} location - human-readable position description.
 * @property {string} galaxy - host galaxy name ("Milky Way", "Andromeda", "Local Group", ...).
 * @property {?string} solarSystem - host star system name, or null if not applicable.
 * @property {number} distanceFromEarthKm - straight-line distance from Earth, km.
 * @property {number} radiusKm - mean radius, km.
 * @property {number} colorHex - base render color.
 * @property {?{ parentId: ?string, semiMajorAxisAu: number, eccentricity?: number, periodDays: number, inclinationDeg?: number, phaseOffset?: number }} orbit
 * @property {{
 *   surfaceTempC: number, atmosphericPressureAtm: number, surfaceGravityG: number,
 *   radiationIndex: number, hasLiquidWater: boolean, isGasGiant: boolean,
 *   composition: Record<string, number>
 * }} environment
 * @property {string} description - short, warm, plain-language blurb.
 * @property {string[]} tags - extra search keywords.
 */

/** @type {CelestialBody[]} */
export const CELESTIAL_BODIES = [
  // =========================================================================
  // SCALE 0 & 1: The Solar System (Sun, Planets, Moons, Dwarf Planets, Comets)
  // =========================================================================
  {
    id: "sun",
    name: "The Sun",
    type: "star",
    scaleTier: 1,
    location: "Center of the Solar System",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 149_597_870,
    radiusKm: 696_340,
    colorHex: 0xffd27a,
    orbit: null,
    environment: {
      surfaceTempC: 5500,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 27.9,
      radiationIndex: 10,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Hydrogen: 73, Helium: 25, Other: 2 },
    },
    description: "A warm, steady G-type yellow dwarf star and the gravitational heart of our home system.",
    tags: ["star", "sol", "home star", "yellow dwarf"],
  },
  {
    id: "mercury",
    name: "Mercury",
    type: "planet",
    scaleTier: 0,
    location: "1st planet from the Sun",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 91_700_000,
    radiusKm: 2439.7,
    colorHex: 0x9c9287,
    orbit: { parentId: "sun", semiMajorAxisAu: 0.387, eccentricity: 0.205, periodDays: 88, inclinationDeg: 7 },
    environment: {
      surfaceTempC: 167,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.38,
      radiationIndex: 8,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Oxygen: 42, Sodium: 29, Hydrogen: 22, Other: 7 },
    },
    description: "The swift, cratered, sun-scorched world closest to our star.",
    tags: ["planet", "inner planet", "terrestrial"],
  },
  {
    id: "venus",
    name: "Venus",
    type: "planet",
    scaleTier: 0,
    location: "2nd planet from the Sun",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 41_400_000,
    radiusKm: 6051.8,
    colorHex: 0xe8c98a,
    orbit: { parentId: "sun", semiMajorAxisAu: 0.723, eccentricity: 0.007, periodDays: 225, inclinationDeg: 3.4 },
    environment: {
      surfaceTempC: 464,
      atmosphericPressureAtm: 92,
      surfaceGravityG: 0.9,
      radiationIndex: 3,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { CO2: 96.5, N2: 3.5 },
    },
    description: "Earth's greenhouse-trapped twin world, hidden under crushing sulfuric acid clouds.",
    tags: ["planet", "inner planet", "greenhouse"],
  },
  {
    id: "earth",
    name: "Earth",
    type: "planet",
    scaleTier: 0,
    location: "3rd planet from the Sun",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 0,
    radiusKm: 6371,
    colorHex: 0x4d90fe,
    orbit: { parentId: "sun", semiMajorAxisAu: 1.0, eccentricity: 0.0167, periodDays: 365.25, inclinationDeg: 0 },
    environment: {
      surfaceTempC: 15,
      atmosphericPressureAtm: 1,
      surfaceGravityG: 1,
      radiationIndex: 1,
      hasLiquidWater: true,
      isGasGiant: false,
      composition: { N2: 78, O2: 21, Argon: 0.9, CO2: 0.04 },
    },
    description: "Home. A dynamic, blue, living world sheltered by oceans and life.",
    tags: ["planet", "home", "habitable", "terrestrial", "ocean world"],
  },
  {
    id: "moon",
    name: "The Moon",
    type: "moon",
    scaleTier: 0,
    location: "Orbiting Earth",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 384_400,
    radiusKm: 1737.4,
    colorHex: 0xbbbbbb,
    orbit: { parentId: "earth", semiMajorAxisAu: 0.00257, eccentricity: 0.055, periodDays: 27.3, inclinationDeg: 5.1 },
    environment: {
      surfaceTempC: -20,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.166,
      radiationIndex: 6,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Trace: 100 },
    },
    description: "Earth's ancient, cratered companion and humanity's first stepping stone into space.",
    tags: ["moon", "luna", "satellite"],
  },
  {
    id: "mars",
    name: "Mars",
    type: "planet",
    scaleTier: 0,
    location: "4th planet from the Sun",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 78_300_000,
    radiusKm: 3389.5,
    colorHex: 0xc1440e,
    orbit: { parentId: "sun", semiMajorAxisAu: 1.524, eccentricity: 0.093, periodDays: 687, inclinationDeg: 1.85 },
    environment: {
      surfaceTempC: -63,
      atmosphericPressureAtm: 0.006,
      surfaceGravityG: 0.38,
      radiationIndex: 5,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { CO2: 95, N2: 2.8, Argon: 2 },
    },
    description: "The rust-red desert planet with ancient dry river valleys, Olympus Mons, and Valles Marineris.",
    tags: ["planet", "red planet", "desert world"],
  },
  {
    id: "phobos",
    name: "Phobos",
    type: "moon",
    scaleTier: 0,
    location: "Orbiting Mars",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 78_300_000,
    radiusKm: 11.3,
    colorHex: 0x8a7a6a,
    orbit: { parentId: "mars", semiMajorAxisAu: 0.0000626, eccentricity: 0.015, periodDays: 0.32, inclinationDeg: 1 },
    environment: {
      surfaceTempC: -40,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.0057,
      radiationIndex: 6,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Trace: 100 },
    },
    description: "A heavily grooved, captured asteroid moon spiraling slowly toward Mars.",
    tags: ["moon", "mars moon"],
  },
  {
    id: "deimos",
    name: "Deimos",
    type: "moon",
    scaleTier: 0,
    location: "Orbiting Mars",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 78_320_000,
    radiusKm: 6.2,
    colorHex: 0x9e9182,
    orbit: { parentId: "mars", semiMajorAxisAu: 0.000156, eccentricity: 0.0002, periodDays: 1.26, inclinationDeg: 1.8 },
    environment: {
      surfaceTempC: -40,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.003,
      radiationIndex: 6,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Trace: 100 },
    },
    description: "The smooth, dust-blanketed outer moon of Mars with very low gravity.",
    tags: ["moon", "mars moon"],
  },
  {
    id: "ceres",
    name: "Ceres",
    type: "dwarfPlanet",
    scaleTier: 1,
    location: "Asteroid Belt",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 263_000_000,
    radiusKm: 469.7,
    colorHex: 0xa9a297,
    orbit: { parentId: "sun", semiMajorAxisAu: 2.77, eccentricity: 0.076, periodDays: 1682, inclinationDeg: 10.6 },
    environment: {
      surfaceTempC: -105,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.029,
      radiationIndex: 5,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Rock: 50, WaterIce: 50 },
    },
    description:
      "The largest object in the asteroid belt, housing bright sodium carbonate salt deposits in Occator Crater.",
    tags: ["dwarf planet", "asteroid belt", "ice world"],
  },
  {
    id: "vesta",
    name: "4 Vesta",
    type: "dwarfPlanet",
    scaleTier: 1,
    location: "Asteroid Belt",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 240_000_000,
    radiusKm: 262.7,
    colorHex: 0x8b857c,
    orbit: { parentId: "sun", semiMajorAxisAu: 2.36, eccentricity: 0.089, periodDays: 1325, inclinationDeg: 7.1 },
    environment: {
      surfaceTempC: -110,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.025,
      radiationIndex: 5,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Basalt: 60, Pyroxene: 40 },
    },
    description: "A differentiated rocky protoplanet with a colossal south polar impact mountain.",
    tags: ["dwarf planet", "protoplanet", "asteroid belt"],
  },
  {
    id: "asteroid-belt",
    name: "The Asteroid Belt",
    type: "asteroidBelt",
    scaleTier: 1,
    location: "Between Mars and Jupiter",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 329_000_000,
    radiusKm: 0,
    colorHex: 0x8f8578,
    orbit: { parentId: "sun", semiMajorAxisAu: 2.7, eccentricity: 0.08, periodDays: 1600, inclinationDeg: 6 },
    environment: {
      surfaceTempC: -100,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 5,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Silicates: 75, Metals: 25 },
    },
    description: "A vast ring of primordial rock and ice remnants drifting between the inner and outer planets.",
    tags: ["asteroids", "belt", "debris"],
  },
  {
    id: "jupiter",
    name: "Jupiter",
    type: "planet",
    scaleTier: 1,
    location: "5th planet from the Sun",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 628_700_000,
    radiusKm: 69_911,
    colorHex: 0xd8ae7e,
    orbit: { parentId: "sun", semiMajorAxisAu: 5.2, eccentricity: 0.049, periodDays: 4333, inclinationDeg: 1.3 },
    environment: {
      surfaceTempC: -108,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 2.53,
      radiationIndex: 9,
      hasLiquidWater: false,
      isGasGiant: true,
      composition: { H2: 90, Helium: 10 },
    },
    description: "The monarch of the Solar System — a colossal gas giant with the centuries-old Great Red Spot storm.",
    tags: ["planet", "gas giant", "outer planet"],
  },
  {
    id: "io",
    name: "Io",
    type: "moon",
    scaleTier: 1,
    location: "Orbiting Jupiter",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 628_300_000,
    radiusKm: 1821.6,
    colorHex: 0xf5d033,
    orbit: {
      parentId: "jupiter",
      semiMajorAxisAu: 0.00282,
      eccentricity: 0.0041,
      periodDays: 1.77,
      inclinationDeg: 0.05,
    },
    environment: {
      surfaceTempC: -143,
      atmosphericPressureAtm: 0.000001,
      surfaceGravityG: 0.183,
      radiationIndex: 10,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Sulfur: 70, Silicates: 30 },
    },
    description: "The most volcanically active body in the Solar System, churned by tidal friction from Jupiter.",
    tags: ["moon", "volcano", "galilean moon"],
  },
  {
    id: "europa",
    name: "Europa",
    type: "moon",
    scaleTier: 1,
    location: "Orbiting Jupiter",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 628_300_000,
    radiusKm: 1560.8,
    colorHex: 0xe4d8c4,
    orbit: {
      parentId: "jupiter",
      semiMajorAxisAu: 0.0045,
      eccentricity: 0.009,
      periodDays: 3.55,
      inclinationDeg: 0.47,
    },
    environment: {
      surfaceTempC: -160,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.134,
      radiationIndex: 7,
      hasLiquidWater: true,
      isGasGiant: false,
      composition: { WaterIce: 85, Silicates: 15 },
    },
    description: "An ice-crusted world hiding a warm global saltwater ocean with twice the water of Earth.",
    tags: ["moon", "ocean world", "galilean moon", "habitable candidate"],
  },
  {
    id: "ganymede",
    name: "Ganymede",
    type: "moon",
    scaleTier: 1,
    location: "Orbiting Jupiter",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 628_500_000,
    radiusKm: 2634.1,
    colorHex: 0x9b9087,
    orbit: {
      parentId: "jupiter",
      semiMajorAxisAu: 0.00715,
      eccentricity: 0.0013,
      periodDays: 7.15,
      inclinationDeg: 0.2,
    },
    environment: {
      surfaceTempC: -163,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.146,
      radiationIndex: 6,
      hasLiquidWater: true,
      isGasGiant: false,
      composition: { WaterIce: 50, SilicateRock: 50 },
    },
    description: "The largest moon in the Solar System — larger than Mercury — with its own generated magnetic field.",
    tags: ["moon", "galilean moon", "magnetic field"],
  },
  {
    id: "callisto",
    name: "Callisto",
    type: "moon",
    scaleTier: 1,
    location: "Orbiting Jupiter",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 628_900_000,
    radiusKm: 2410.3,
    colorHex: 0x6e655b,
    orbit: {
      parentId: "jupiter",
      semiMajorAxisAu: 0.01258,
      eccentricity: 0.0074,
      periodDays: 16.69,
      inclinationDeg: 0.28,
    },
    environment: {
      surfaceTempC: -171,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.126,
      radiationIndex: 3,
      hasLiquidWater: true,
      isGasGiant: false,
      composition: { WaterIce: 50, Rock: 50 },
    },
    description: "A dark, heavily cratered ancient ice moon with the gigantic multi-ring Valhalla impact structure.",
    tags: ["moon", "galilean moon", "ancient"],
  },
  {
    id: "saturn",
    name: "Saturn",
    type: "planet",
    scaleTier: 1,
    location: "6th planet from the Sun",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 1_275_000_000,
    radiusKm: 58_232,
    colorHex: 0xead6a8,
    orbit: { parentId: "sun", semiMajorAxisAu: 9.58, eccentricity: 0.057, periodDays: 10_759, inclinationDeg: 2.5 },
    environment: {
      surfaceTempC: -139,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 1.06,
      radiationIndex: 8,
      hasLiquidWater: false,
      isGasGiant: true,
      composition: { H2: 96, Helium: 3, Other: 1 },
    },
    description: "The ringed jewel of the solar system, crowned with brilliant crystalline ice ringlets.",
    tags: ["planet", "rings", "gas giant"],
  },
  {
    id: "enceladus",
    name: "Enceladus",
    type: "moon",
    scaleTier: 1,
    location: "Orbiting Saturn",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 1_275_000_000,
    radiusKm: 252.1,
    colorHex: 0xfafaff,
    orbit: {
      parentId: "saturn",
      semiMajorAxisAu: 0.00159,
      eccentricity: 0.0047,
      periodDays: 1.37,
      inclinationDeg: 0.01,
    },
    environment: {
      surfaceTempC: -198,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.0113,
      radiationIndex: 4,
      hasLiquidWater: true,
      isGasGiant: false,
      composition: { WaterIce: 95, Organics: 5 },
    },
    description: "A dazzling snow-white moon spraying organic-rich water vapor geysers from southern tiger stripes.",
    tags: ["moon", "cryovolcanism", "ocean world", "geysers"],
  },
  {
    id: "mimas",
    name: "Mimas",
    type: "moon",
    scaleTier: 1,
    location: "Orbiting Saturn",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 1_275_000_000,
    radiusKm: 198.2,
    colorHex: 0xb5a99d,
    orbit: { parentId: "saturn", semiMajorAxisAu: 0.00124, eccentricity: 0.02, periodDays: 0.94, inclinationDeg: 1.57 },
    environment: {
      surfaceTempC: -209,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.0065,
      radiationIndex: 4,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { WaterIce: 90, Rock: 10 },
    },
    description: "Saturn's 'Death Star' moon, dominated by the colossal 130-km wide Herschel crater.",
    tags: ["moon", "crater"],
  },
  {
    id: "titan",
    name: "Titan",
    type: "moon",
    scaleTier: 1,
    location: "Orbiting Saturn",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 1_275_000_000,
    radiusKm: 2574.7,
    colorHex: 0xe0a95c,
    orbit: {
      parentId: "saturn",
      semiMajorAxisAu: 0.00817,
      eccentricity: 0.028,
      periodDays: 15.9,
      inclinationDeg: 0.35,
    },
    environment: {
      surfaceTempC: -179,
      atmosphericPressureAtm: 1.45,
      surfaceGravityG: 0.14,
      radiationIndex: 3,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { N2: 95, CH4: 5 },
    },
    description: "A golden smog-wrapped moon with methane rain, rivers, and tranquil hydrocarbon seas.",
    tags: ["moon", "methane lakes", "dense atmosphere"],
  },
  {
    id: "iapetus",
    name: "Iapetus",
    type: "moon",
    scaleTier: 1,
    location: "Orbiting Saturn",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 1_275_000_000,
    radiusKm: 734.5,
    colorHex: 0x6e5d48,
    orbit: {
      parentId: "saturn",
      semiMajorAxisAu: 0.0238,
      eccentricity: 0.028,
      periodDays: 79.3,
      inclinationDeg: 15.47,
    },
    environment: {
      surfaceTempC: -180,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.0227,
      radiationIndex: 3,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { WaterIce: 80, Carbonaceous: 20 },
    },
    description:
      "The yin-yang moon with one coal-dark hemisphere, one bright icy hemisphere, and a giant equatorial ridge.",
    tags: ["moon", "two-tone", "equatorial ridge"],
  },
  {
    id: "uranus",
    name: "Uranus",
    type: "planet",
    scaleTier: 1,
    location: "7th planet from the Sun",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 2_720_000_000,
    radiusKm: 25_362,
    colorHex: 0xa9d8d8,
    orbit: { parentId: "sun", semiMajorAxisAu: 19.2, eccentricity: 0.047, periodDays: 30_687, inclinationDeg: 0.77 },
    environment: {
      surfaceTempC: -197,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.89,
      radiationIndex: 7,
      hasLiquidWater: false,
      isGasGiant: true,
      composition: { H2: 82.5, Helium: 15.2, CH4: 2.3 },
    },
    description: "A serene, pale-cyan ice giant rolling around the Sun on its tilted side.",
    tags: ["planet", "ice giant"],
  },
  {
    id: "miranda",
    name: "Miranda",
    type: "moon",
    scaleTier: 1,
    location: "Orbiting Uranus",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 2_720_000_000,
    radiusKm: 235.8,
    colorHex: 0xa2a9b2,
    orbit: {
      parentId: "uranus",
      semiMajorAxisAu: 0.000865,
      eccentricity: 0.0013,
      periodDays: 1.41,
      inclinationDeg: 4.34,
    },
    environment: {
      surfaceTempC: -213,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.008,
      radiationIndex: 4,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { WaterIce: 60, Silicates: 40 },
    },
    description:
      "A jumbled Frankenstein moon of mismatched terrain featuring the sheer 20-km high Verona Rupes cliffs.",
    tags: ["moon", "cliffs", "uranus moon"],
  },
  {
    id: "neptune",
    name: "Neptune",
    type: "planet",
    scaleTier: 1,
    location: "8th planet from the Sun",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 4_350_000_000,
    radiusKm: 24_622,
    colorHex: 0x5b7fe0,
    orbit: { parentId: "sun", semiMajorAxisAu: 30.05, eccentricity: 0.009, periodDays: 60_190, inclinationDeg: 1.77 },
    environment: {
      surfaceTempC: -201,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 1.14,
      radiationIndex: 7,
      hasLiquidWater: false,
      isGasGiant: true,
      composition: { H2: 80, Helium: 19, CH4: 1 },
    },
    description: "A vibrant azure ice giant lashed by supersonic storms and raging jet streams.",
    tags: ["planet", "ice giant"],
  },
  {
    id: "triton",
    name: "Triton",
    type: "moon",
    scaleTier: 1,
    location: "Orbiting Neptune",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 4_350_000_000,
    radiusKm: 1353.4,
    colorHex: 0xbac9cc,
    orbit: {
      parentId: "neptune",
      semiMajorAxisAu: 0.00237,
      eccentricity: 0.000016,
      periodDays: 5.88,
      inclinationDeg: 156.8,
    },
    environment: {
      surfaceTempC: -235,
      atmosphericPressureAtm: 0.000014,
      surfaceGravityG: 0.079,
      radiationIndex: 4,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { NitrogenIce: 55, WaterIce: 35, CO2: 10 },
    },
    description:
      "A captured retrograde Kuiper Belt world erupting active cryo-nitrogen geysers across cantaloupe terrain.",
    tags: ["moon", "retrograde", "geysers", "kuiper belt"],
  },
  {
    id: "pluto",
    name: "Pluto",
    type: "dwarfPlanet",
    scaleTier: 1,
    location: "Kuiper Belt",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 5_900_000_000,
    radiusKm: 1188.3,
    colorHex: 0xcbb193,
    orbit: { parentId: "sun", semiMajorAxisAu: 39.5, eccentricity: 0.249, periodDays: 90_560, inclinationDeg: 17.2 },
    environment: {
      surfaceTempC: -229,
      atmosphericPressureAtm: 0.00001,
      surfaceGravityG: 0.063,
      radiationIndex: 5,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { N2: 98, CH4: 1.5, CO: 0.5 },
    },
    description:
      "A complex icy world at the Kuiper Belt frontier with nitrogen glaciers and the famous Tombaugh Regio heart.",
    tags: ["dwarf planet", "kuiper belt", "heart"],
  },
  {
    id: "charon",
    name: "Charon",
    type: "moon",
    scaleTier: 1,
    location: "Orbiting Pluto",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 5_900_000_000,
    radiusKm: 606,
    colorHex: 0x9e9185,
    orbit: { parentId: "pluto", semiMajorAxisAu: 0.00013, eccentricity: 0.0002, periodDays: 6.38, inclinationDeg: 0.0 },
    environment: {
      surfaceTempC: -230,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.029,
      radiationIndex: 4,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { WaterIce: 85, Organics: 15 },
    },
    description:
      "Pluto's mutually tidally locked binary partner, marked by the reddish Mordor Macula north polar region.",
    tags: ["moon", "binary planet", "kuiper belt"],
  },
  {
    id: "eris",
    name: "Eris",
    type: "dwarfPlanet",
    scaleTier: 1,
    location: "Scattered Disc",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 14_400_000_000,
    radiusKm: 1163,
    colorHex: 0xeae6df,
    orbit: { parentId: "sun", semiMajorAxisAu: 67.8, eccentricity: 0.44, periodDays: 203_830, inclinationDeg: 44.0 },
    environment: {
      surfaceTempC: -243,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.084,
      radiationIndex: 4,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { MethaneIce: 70, NitrogenIce: 30 },
    },
    description:
      "A massive, ultra-reflective scattered disc dwarf planet whose 2005 discovery led to the modern definition of a planet.",
    tags: ["dwarf planet", "scattered disc", "trans-neptunian"],
  },
  {
    id: "haumea",
    name: "Haumea",
    type: "dwarfPlanet",
    scaleTier: 1,
    location: "Kuiper Belt",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 7_500_000_000,
    radiusKm: 816,
    colorHex: 0xd9e3eb,
    orbit: { parentId: "sun", semiMajorAxisAu: 43.1, eccentricity: 0.19, periodDays: 103_770, inclinationDeg: 28.2 },
    environment: {
      surfaceTempC: -240,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.045,
      radiationIndex: 4,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { WaterIce: 90, Rock: 10 },
    },
    description:
      "A bizarre, rapid-spinning football-shaped dwarf planet with crystalline ice rings and a 3.9-hour day.",
    tags: ["dwarf planet", "rings", "fast rotator", "kuiper belt"],
  },
  {
    id: "makemake",
    name: "Makemake",
    type: "dwarfPlanet",
    scaleTier: 1,
    location: "Kuiper Belt",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 7_800_000_000,
    radiusKm: 715,
    colorHex: 0xd27d53,
    orbit: { parentId: "sun", semiMajorAxisAu: 45.4, eccentricity: 0.16, periodDays: 112_897, inclinationDeg: 29.0 },
    environment: {
      surfaceTempC: -239,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.051,
      radiationIndex: 4,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { MethaneIce: 80, EthaneIce: 20 },
    },
    description: "A brilliant reddish methane-snow world in the Kuiper Belt named after the Rapa Nui creator god.",
    tags: ["dwarf planet", "kuiper belt", "methane ice"],
  },
  {
    id: "sedna",
    name: "90377 Sedna",
    type: "dwarfPlanet",
    scaleTier: 1,
    location: "Inner Oort Cloud",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 13_000_000_000,
    radiusKm: 498,
    colorHex: 0xb54d3b,
    orbit: { parentId: "sun", semiMajorAxisAu: 506, eccentricity: 0.85, periodDays: 4_160_000, inclinationDeg: 11.9 },
    environment: {
      surfaceTempC: -240,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.034,
      radiationIndex: 3,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Tholins: 60, WaterIce: 40 },
    },
    description:
      "One of the most distant known objects in the Solar System on an extreme 11,400-year inner Oort cloud orbit.",
    tags: ["dwarf planet", "oort cloud", "extreme orbit"],
  },
  {
    id: "halley-comet",
    name: "Halley's Comet (1P/Halley)",
    type: "dwarfPlanet",
    scaleTier: 1,
    location: "Solar System (Periodic)",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 5_200_000_000,
    radiusKm: 5.5,
    colorHex: 0x90a4ae,
    orbit: { parentId: "sun", semiMajorAxisAu: 17.8, eccentricity: 0.967, periodDays: 27_500, inclinationDeg: 162.3 },
    environment: {
      surfaceTempC: -150,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.0003,
      radiationIndex: 5,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { WaterIce: 80, CO: 10, Carbon: 10 },
    },
    description: "Humanity's most famous periodic comet, lighting up Earth's skies every 75-76 years.",
    tags: ["comet", "periodic", "dirty snowball"],
  },
  {
    id: "oumuamua",
    name: "'Oumuamua (1I/2017 U1)",
    type: "dwarfPlanet",
    scaleTier: 1,
    location: "Exiting Solar System",
    galaxy: "Milky Way",
    solarSystem: null,
    distanceFromEarthKm: 4_500_000_000,
    radiusKm: 0.2,
    colorHex: 0x995544,
    orbit: null,
    environment: {
      surfaceTempC: -220,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.00001,
      radiationIndex: 4,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { CarbonaceousTholins: 100 },
    },
    description:
      "The first interstellar visitor ever detected passing through our Solar System from deep interstellar space.",
    tags: ["interstellar visitor", "asteroid", "hyperbolic"],
  },
  {
    id: "comet-67p",
    name: "Comet 67P/Churyumov–Gerasimenko",
    type: "dwarfPlanet",
    scaleTier: 1,
    location: "Jupiter-family Comet",
    galaxy: "Milky Way",
    solarSystem: "Sol",
    distanceFromEarthKm: 580_000_000,
    radiusKm: 2.1,
    colorHex: 0x5a5550,
    orbit: { parentId: "sun", semiMajorAxisAu: 3.46, eccentricity: 0.64, periodDays: 2356, inclinationDeg: 7.04 },
    environment: {
      surfaceTempC: -120,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.0001,
      radiationIndex: 5,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Organics: 45, Silicates: 45, WaterIce: 10 },
    },
    description: "The rubber-duck shaped comet rendezvoused with by ESA's Rosetta spacecraft and lander Philae.",
    tags: ["comet", "rosetta", "philae"],
  },

  // =========================================================================
  // SCALE 2: Stellar Neighborhood, Exoplanets, Stars, Pulsars, Black Holes, Nebulae
  // =========================================================================
  {
    id: "proxima-centauri",
    name: "Proxima Centauri",
    type: "star",
    scaleTier: 2,
    location: "Nearest star to the Sun",
    galaxy: "Milky Way",
    solarSystem: "Alpha Centauri",
    distanceFromEarthKm: 39_920_000_000_000,
    radiusKm: 107_000,
    colorHex: 0xff6b4a,
    orbit: null,
    environment: {
      surfaceTempC: 2800,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 45,
      radiationIndex: 9,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Hydrogen: 74, Helium: 25, Other: 1 },
    },
    description: "A flare-active red dwarf star and humanity's closest stellar neighbor at 4.24 light-years.",
    tags: ["star", "red dwarf", "closest star"],
  },
  {
    id: "proxima-b",
    name: "Proxima Centauri b",
    type: "planet",
    scaleTier: 2,
    location: "Orbiting Proxima Centauri",
    galaxy: "Milky Way",
    solarSystem: "Alpha Centauri",
    distanceFromEarthKm: 39_920_000_000_000,
    radiusKm: 7000,
    colorHex: 0x8fa4c9,
    orbit: {
      parentId: "proxima-centauri",
      semiMajorAxisAu: 0.0485,
      eccentricity: 0.02,
      periodDays: 11.2,
      inclinationDeg: 0,
    },
    environment: {
      surfaceTempC: -39,
      atmosphericPressureAtm: 0.6,
      surfaceGravityG: 1.1,
      radiationIndex: 7,
      hasLiquidWater: true,
      isGasGiant: false,
      composition: { N2: 60, CO2: 30, Other: 10 },
    },
    description: "A terrestrial exoplanet orbiting in Proxima's habitable zone, receiving frequent stellar flares.",
    tags: ["exoplanet", "planet", "habitable zone", "terrestrial"],
  },
  {
    id: "alpha-centauri-a",
    name: "Alpha Centauri A (Rigil Kentaurus)",
    type: "star",
    scaleTier: 2,
    location: "Alpha Centauri system",
    galaxy: "Milky Way",
    solarSystem: "Alpha Centauri",
    distanceFromEarthKm: 41_100_000_000_000,
    radiusKm: 855_000,
    colorHex: 0xfff2d0,
    orbit: null,
    environment: {
      surfaceTempC: 5800,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 24,
      radiationIndex: 10,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Hydrogen: 71, Helium: 27, Other: 2 },
    },
    description: "A bright yellow-orange G-type star slightly larger than our Sun in a close binary dance.",
    tags: ["star", "binary star", "solar twin"],
  },
  {
    id: "alpha-centauri-b",
    name: "Alpha Centauri B (Toliman)",
    type: "star",
    scaleTier: 2,
    location: "Alpha Centauri system",
    galaxy: "Milky Way",
    solarSystem: "Alpha Centauri",
    distanceFromEarthKm: 41_100_000_000_000,
    radiusKm: 600_000,
    colorHex: 0xffa550,
    orbit: null,
    environment: {
      surfaceTempC: 5260,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 30,
      radiationIndex: 10,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Hydrogen: 72, Helium: 26, Other: 2 },
    },
    description: "The orange K-dwarf companion star to Alpha Centauri A.",
    tags: ["star", "k dwarf", "binary star"],
  },
  {
    id: "barnards-star",
    name: "Barnard's Star",
    type: "star",
    scaleTier: 2,
    location: "Ophiuchus",
    galaxy: "Milky Way",
    solarSystem: "Barnard",
    distanceFromEarthKm: 56_400_000_000_000,
    radiusKm: 136_000,
    colorHex: 0xff5533,
    orbit: null,
    environment: {
      surfaceTempC: 3100,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 40,
      radiationIndex: 8,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Hydrogen: 74, Helium: 25, Metals: 1 },
    },
    description: "An ancient red dwarf possessing the fastest known proper motion across Earth's night sky.",
    tags: ["star", "red dwarf", "high proper motion"],
  },
  {
    id: "trappist-1",
    name: "TRAPPIST-1",
    type: "star",
    scaleTier: 2,
    location: "Aquarius",
    galaxy: "Milky Way",
    solarSystem: "TRAPPIST-1",
    distanceFromEarthKm: 3.73e14,
    radiusKm: 84_000,
    colorHex: 0xff3b30,
    orbit: null,
    environment: {
      surfaceTempC: 2280,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 60,
      radiationIndex: 8,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Hydrogen: 75, Helium: 24, Other: 1 },
    },
    description: "An ultra-cool red dwarf star hosting a famous resonant system of 7 Earth-sized terrestrial planets.",
    tags: ["star", "ultra-cool dwarf", "trappist"],
  },
  {
    id: "trappist-1e",
    name: "TRAPPIST-1e",
    type: "planet",
    scaleTier: 2,
    location: "Orbiting TRAPPIST-1",
    galaxy: "Milky Way",
    solarSystem: "TRAPPIST-1",
    distanceFromEarthKm: 3.73e14,
    radiusKm: 5850,
    colorHex: 0x3d7ecc,
    orbit: {
      parentId: "trappist-1",
      semiMajorAxisAu: 0.029,
      eccentricity: 0.005,
      periodDays: 6.1,
      inclinationDeg: 89.8,
    },
    environment: {
      surfaceTempC: -22,
      atmosphericPressureAtm: 1.1,
      surfaceGravityG: 0.93,
      radiationIndex: 4,
      hasLiquidWater: true,
      isGasGiant: false,
      composition: { N2: 70, O2: 18, CO2: 10, WaterVapor: 2 },
    },
    description:
      "One of the most promising potentially habitable Earth-sized exoplanets known, with liquid water potential.",
    tags: ["exoplanet", "habitable zone", "earth analog", "trappist"],
  },
  {
    id: "trappist-1f",
    name: "TRAPPIST-1f",
    type: "planet",
    scaleTier: 2,
    location: "Orbiting TRAPPIST-1",
    galaxy: "Milky Way",
    solarSystem: "TRAPPIST-1",
    distanceFromEarthKm: 3.73e14,
    radiusKm: 6660,
    colorHex: 0x76a5af,
    orbit: {
      parentId: "trappist-1",
      semiMajorAxisAu: 0.038,
      eccentricity: 0.01,
      periodDays: 9.2,
      inclinationDeg: 89.7,
    },
    environment: {
      surfaceTempC: -54,
      atmosphericPressureAtm: 1.5,
      surfaceGravityG: 0.88,
      radiationIndex: 3,
      hasLiquidWater: true,
      isGasGiant: false,
      composition: { WaterIce: 40, Silicates: 60 },
    },
    description:
      "A temperate water-rich world in the TRAPPIST-1 system, likely wrapped in a global deep ocean or ice shell.",
    tags: ["exoplanet", "ocean world", "trappist"],
  },
  {
    id: "kepler-452b",
    name: "Kepler-452b",
    type: "planet",
    scaleTier: 2,
    location: "Cygnus",
    galaxy: "Milky Way",
    solarSystem: "Kepler-452",
    distanceFromEarthKm: 1.7e16,
    radiusKm: 10_380,
    colorHex: 0x4a9d70,
    orbit: null,
    environment: {
      surfaceTempC: -8,
      atmosphericPressureAtm: 2.0,
      surfaceGravityG: 1.9,
      radiationIndex: 2,
      hasLiquidWater: true,
      isGasGiant: false,
      composition: { N2: 75, O2: 15, CO2: 10 },
    },
    description:
      "'Earth's Older Cousin' — a super-Earth in the habitable zone of a G2-type sun-like star 1,800 light-years away.",
    tags: ["exoplanet", "super-earth", "habitable zone", "earth cousin"],
  },
  {
    id: "kepler-22b",
    name: "Kepler-22b",
    type: "planet",
    scaleTier: 2,
    location: "Cygnus",
    galaxy: "Milky Way",
    solarSystem: "Kepler-22",
    distanceFromEarthKm: 5.9e15,
    radiusKm: 15_290,
    colorHex: 0x3b9cb8,
    orbit: null,
    environment: {
      surfaceTempC: 22,
      atmosphericPressureAtm: 5.0,
      surfaceGravityG: 1.8,
      radiationIndex: 2,
      hasLiquidWater: true,
      isGasGiant: false,
      composition: { Water: 60, H2_He: 25, Silicates: 15 },
    },
    description:
      "The first confirmed exoplanet discovered by NASA's Kepler mission in the comfortable habitable zone of a sun-like star.",
    tags: ["exoplanet", "ocean world", "habitable zone"],
  },
  {
    id: "kepler-186f",
    name: "Kepler-186f",
    type: "planet",
    scaleTier: 2,
    location: "Cygnus",
    galaxy: "Milky Way",
    solarSystem: "Kepler-186",
    distanceFromEarthKm: 5.5e15,
    radiusKm: 7450,
    colorHex: 0x8ea876,
    orbit: null,
    environment: {
      surfaceTempC: -46,
      atmosphericPressureAtm: 1.0,
      surfaceGravityG: 1.15,
      radiationIndex: 3,
      hasLiquidWater: true,
      isGasGiant: false,
      composition: { N2: 76, CO2: 20, O2: 4 },
    },
    description: "The historic first validated Earth-sized planet found in the habitable zone of an M-dwarf star.",
    tags: ["exoplanet", "earth-sized", "habitable zone"],
  },
  {
    id: "55-cancri-e",
    name: "55 Cancri e (Janssen)",
    type: "planet",
    scaleTier: 2,
    location: "Cancer",
    galaxy: "Milky Way",
    solarSystem: "Copernicus",
    distanceFromEarthKm: 3.88e14,
    radiusKm: 12_000,
    colorHex: 0xff4500,
    orbit: null,
    environment: {
      surfaceTempC: 2300,
      atmosphericPressureAtm: 100,
      surfaceGravityG: 2.2,
      radiationIndex: 10,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { CarbonLava: 50, SilicateLava: 30, Iron: 20 },
    },
    description:
      "A super-hot, carbon-rich lava super-Earth with molten oceans on its dayside and possible diamond interior mantle.",
    tags: ["exoplanet", "lava world", "diamond planet", "super-earth"],
  },
  {
    id: "hd-189733-b",
    name: "HD 189733 b",
    type: "planet",
    scaleTier: 2,
    location: "Vulpecula",
    galaxy: "Milky Way",
    solarSystem: "HD 189733",
    distanceFromEarthKm: 6.1e14,
    radiusKm: 80_500,
    colorHex: 0x1c58d9,
    orbit: null,
    environment: {
      surfaceTempC: 930,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 2.1,
      radiationIndex: 9,
      hasLiquidWater: false,
      isGasGiant: true,
      composition: { SilicateClouds: 40, H2: 50, Methane: 10 },
    },
    description:
      "A cobalt-blue hot Jupiter where supersonic 8,700 km/h winds blow sideways showers of molten silicate glass.",
    tags: ["exoplanet", "hot jupiter", "glass rain", "cobalt blue"],
  },
  {
    id: "wasp-76b",
    name: "WASP-76b",
    type: "planet",
    scaleTier: 2,
    location: "Pisces",
    galaxy: "Milky Way",
    solarSystem: "WASP-76",
    distanceFromEarthKm: 6.0e15,
    radiusKm: 130_000,
    colorHex: 0xb23b23,
    orbit: null,
    environment: {
      surfaceTempC: 2400,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.6,
      radiationIndex: 10,
      hasLiquidWater: false,
      isGasGiant: true,
      composition: { IronVapor: 30, H2: 60, Helium: 10 },
    },
    description:
      "An ultra-hot gas giant with dayside temperatures exceeding 2400°C where vaporized iron condenses into nightside iron rain.",
    tags: ["exoplanet", "ultra-hot jupiter", "iron rain"],
  },
  {
    id: "k2-18b",
    name: "K2-18b",
    type: "planet",
    scaleTier: 2,
    location: "Leo",
    galaxy: "Milky Way",
    solarSystem: "K2-18",
    distanceFromEarthKm: 1.17e15,
    radiusKm: 16_600,
    colorHex: 0x4682b4,
    orbit: null,
    environment: {
      surfaceTempC: -7,
      atmosphericPressureAtm: 15,
      surfaceGravityG: 1.3,
      radiationIndex: 4,
      hasLiquidWater: true,
      isGasGiant: false,
      composition: { H2_He: 50, Methane: 25, CO2: 20, WaterVapor: 5 },
    },
    description:
      "A candidate Hycean sub-Neptune exoplanet with detected atmospheric methane and carbon dioxide in its habitable zone.",
    tags: ["exoplanet", "hycean", "habitable zone", "sub-neptune"],
  },
  {
    id: "psr-b1257-12-c",
    name: "PSR B1257+12 c (Poltergeist)",
    type: "planet",
    scaleTier: 2,
    location: "Virgo",
    galaxy: "Milky Way",
    solarSystem: "Lich",
    distanceFromEarthKm: 2.18e16,
    radiusKm: 10_200,
    colorHex: 0x708090,
    orbit: null,
    environment: {
      surfaceTempC: -120,
      atmosphericPressureAtm: 0.1,
      surfaceGravityG: 2.8,
      radiationIndex: 10,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { HeavyMetals: 80, Silicates: 20 },
    },
    description:
      "A zombie super-Earth orbiting a rapidly spinning pulsar, bathed in lethal relativistic magnetic particle beams.",
    tags: ["exoplanet", "pulsar planet", "extreme", "zombie world"],
  },
  {
    id: "sirius-a",
    name: "Sirius A",
    type: "star",
    scaleTier: 2,
    location: "Canis Major",
    galaxy: "Milky Way",
    solarSystem: "Sirius",
    distanceFromEarthKm: 81_500_000_000_000,
    radiusKm: 1_192_000,
    colorHex: 0xcfe8ff,
    orbit: null,
    environment: {
      surfaceTempC: 9940,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 4.5,
      radiationIndex: 10,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Hydrogen: 70, Helium: 28, Other: 2 },
    },
    description: "The brightest star in Earth's night sky, blazing blue-white 8.6 light-years away.",
    tags: ["star", "brightest star", "a-type star"],
  },
  {
    id: "vega",
    name: "Vega (Alpha Lyrae)",
    type: "star",
    scaleTier: 2,
    location: "Lyra",
    galaxy: "Milky Way",
    solarSystem: "Vega",
    distanceFromEarthKm: 2.37e14,
    radiusKm: 1_643_000,
    colorHex: 0xd6e8ff,
    orbit: null,
    environment: {
      surfaceTempC: 9600,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 3.5,
      radiationIndex: 10,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Hydrogen: 72, Helium: 26, Metals: 2 },
    },
    description: "A rapid-spinning oblate blue-white star with an extensive circumstellar dust and debris ring.",
    tags: ["star", "standard candle", "debris ring"],
  },
  {
    id: "rigel",
    name: "Rigel (Beta Orionis)",
    type: "star",
    scaleTier: 2,
    location: "Orion",
    galaxy: "Milky Way",
    solarSystem: "Rigel",
    distanceFromEarthKm: 8.17e15,
    radiusKm: 54_900_000,
    colorHex: 0x9bc2ff,
    orbit: null,
    environment: {
      surfaceTempC: 12100,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.1,
      radiationIndex: 10,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Hydrogen: 68, Helium: 30, Other: 2 },
    },
    description:
      "A super-luminous blue supergiant star outshining our Sun by 120,000 times, lighting up the Orion region.",
    tags: ["star", "blue supergiant", "orion"],
  },
  {
    id: "betelgeuse",
    name: "Betelgeuse (Alpha Orionis)",
    type: "star",
    scaleTier: 2,
    location: "Orion",
    galaxy: "Milky Way",
    solarSystem: null,
    distanceFromEarthKm: 3_781_000_000_000_000,
    radiusKm: 617_000_000,
    colorHex: 0xff6a3c,
    orbit: null,
    environment: {
      surfaceTempC: 3500,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.02,
      radiationIndex: 9,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Hydrogen: 60, Helium: 38, Other: 2 },
    },
    description:
      "A gigantic, pulsating red supergiant in Orion's shoulder destined to explode as a dramatic supernova.",
    tags: ["star", "red supergiant", "supernova candidate"],
  },
  {
    id: "antares",
    name: "Antares (Alpha Scorpii)",
    type: "star",
    scaleTier: 2,
    location: "Scorpius",
    galaxy: "Milky Way",
    solarSystem: null,
    distanceFromEarthKm: 5.2e15,
    radiusKm: 473_000_000,
    colorHex: 0xff5333,
    orbit: null,
    environment: {
      surfaceTempC: 3400,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.015,
      radiationIndex: 9,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Hydrogen: 62, Helium: 36, Other: 2 },
    },
    description:
      "The fiery red heart of Scorpius — an immense red supergiant star over 600 times the diameter of our Sun.",
    tags: ["star", "red supergiant", "scorpius"],
  },
  {
    id: "aldebaran",
    name: "Aldebaran (Alpha Tauri)",
    type: "star",
    scaleTier: 2,
    location: "Taurus",
    galaxy: "Milky Way",
    solarSystem: "Aldebaran",
    distanceFromEarthKm: 6.18e14,
    radiusKm: 30_700_000,
    colorHex: 0xff8c42,
    orbit: null,
    environment: {
      surfaceTempC: 3900,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.2,
      radiationIndex: 9,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Hydrogen: 69, Helium: 29, Other: 2 },
    },
    description: "The brilliant orange giant star marking the fiery eye of the Bull in the constellation Taurus.",
    tags: ["star", "orange giant", "taurus"],
  },
  {
    id: "polaris",
    name: "Polaris (The North Star)",
    type: "star",
    scaleTier: 2,
    location: "Ursa Minor",
    galaxy: "Milky Way",
    solarSystem: "Polaris",
    distanceFromEarthKm: 4.07e15,
    radiusKm: 26_100_000,
    colorHex: 0xfff4db,
    orbit: null,
    environment: {
      surfaceTempC: 6015,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.5,
      radiationIndex: 9,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Hydrogen: 70, Helium: 28, Metals: 2 },
    },
    description:
      "The iconic northern navigation star — a classic Cepheid variable supergiant leading a triple star system.",
    tags: ["star", "north star", "cepheid variable", "navigation"],
  },
  {
    id: "stephenson-2-18",
    name: "Stephenson 2-18",
    type: "star",
    scaleTier: 2,
    location: "Scutum",
    galaxy: "Milky Way",
    solarSystem: null,
    distanceFromEarthKm: 1.8e17,
    radiusKm: 1_496_000_000,
    colorHex: 0xff4820,
    orbit: null,
    environment: {
      surfaceTempC: 3200,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0.001,
      radiationIndex: 9,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Hydrogen: 55, Helium: 43, Other: 2 },
    },
    description:
      "One of the largest known stars in the universe — a red hypergiant large enough to engulf Saturn's orbit.",
    tags: ["star", "hypergiant", "largest star"],
  },
  {
    id: "r136a1",
    name: "R136a1",
    type: "star",
    scaleTier: 2,
    location: "Tarantula Nebula (LMC)",
    galaxy: "Large Magellanic Cloud",
    solarSystem: null,
    distanceFromEarthKm: 1.54e18,
    radiusKm: 29_700_000,
    colorHex: 0x88bbff,
    orbit: null,
    environment: {
      surfaceTempC: 46000,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 3.5,
      radiationIndex: 10,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Hydrogen: 60, Helium: 38, Metals: 2 },
    },
    description:
      "The most massive known star in the universe (~200 solar masses), radiating with blinding Wolf-Rayet winds.",
    tags: ["star", "most massive", "wolf-rayet"],
  },
  {
    id: "crab-pulsar",
    name: "Crab Pulsar (PSR B0531+21)",
    type: "star",
    scaleTier: 2,
    location: "Crab Nebula (Taurus)",
    galaxy: "Milky Way",
    solarSystem: null,
    distanceFromEarthKm: 6.15e16,
    radiusKm: 10,
    colorHex: 0x73e6ff,
    orbit: null,
    environment: {
      surfaceTempC: 1000000,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 200_000_000_000,
      radiationIndex: 10,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Neutrons: 95, SuperconductingProtons: 5 },
    },
    description:
      "A super-dense neutron star spinning 30 times per second, emitting flashing lighthouse beams of gamma and X-rays.",
    tags: ["pulsar", "neutron star", "supernova remnant"],
  },
  {
    id: "sgr-1806-20",
    name: "SGR 1806-20 (Magnetar)",
    type: "star",
    scaleTier: 2,
    location: "Sagittarius",
    galaxy: "Milky Way",
    solarSystem: null,
    distanceFromEarthKm: 4.7e17,
    radiusKm: 12,
    colorHex: 0xff00ff,
    orbit: null,
    environment: {
      surfaceTempC: 2000000,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 300_000_000_000,
      radiationIndex: 10,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { DegenerateMatter: 100 },
    },
    description:
      "An ultra-magnetic neutron star with magnetic fields a quadrillion times stronger than Earth, producing colossal starquakes.",
    tags: ["magnetar", "neutron star", "extreme magnetism"],
  },
  {
    id: "cygnus-x1",
    name: "Cygnus X-1",
    type: "blackHole",
    scaleTier: 2,
    location: "Cygnus",
    galaxy: "Milky Way",
    solarSystem: null,
    distanceFromEarthKm: 5.76e16,
    radiusKm: 44,
    colorHex: 0x111118,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: Infinity,
      radiationIndex: 10,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Singularity: 100 },
    },
    description:
      "The first widely accepted stellar-mass black hole, violently feeding from its blue supergiant companion star.",
    tags: ["black hole", "stellar mass", "x-ray binary"],
  },
  {
    id: "sagittarius-a-star",
    name: "Sagittarius A*",
    type: "blackHole",
    scaleTier: 2,
    location: "Galactic Center",
    galaxy: "Milky Way",
    solarSystem: null,
    distanceFromEarthKm: 2.466e17,
    radiusKm: 12_000_000,
    colorHex: 0x1a1a22,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: Infinity,
      radiationIndex: 10,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Singularity: 100 },
    },
    description: "The 4-million-solar-mass supermassive black hole anchoring the gravitational core of our Milky Way.",
    tags: ["black hole", "galactic center", "supermassive black hole"],
  },
  {
    id: "eagle-nebula",
    name: "Eagle Nebula (Pillars of Creation / M16)",
    type: "nebula",
    scaleTier: 2,
    location: "Serpens",
    galaxy: "Milky Way",
    solarSystem: null,
    distanceFromEarthKm: 6.803e16,
    radiusKm: 4.5e13,
    colorHex: 0xd88b5a,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 6,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Hydrogen: 90, Dust: 10 },
    },
    description: "Towering gas and cosmic dust pillars where new infant stars are carved out of interstellar clouds.",
    tags: ["nebula", "pillars of creation", "star nursery"],
  },
  {
    id: "orion-nebula",
    name: "Orion Nebula (M42)",
    type: "nebula",
    scaleTier: 2,
    location: "Orion",
    galaxy: "Milky Way",
    solarSystem: null,
    distanceFromEarthKm: 1.29e16,
    radiusKm: 1.2e13,
    colorHex: 0xff9ad1,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 6,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Hydrogen: 92, Dust: 8 },
    },
    description: "A brilliant, luminous stellar nursery visible to the naked eye as the middle star in Orion's sword.",
    tags: ["nebula", "star nursery", "orion"],
  },
  {
    id: "carina-nebula",
    name: "Carina Nebula (NGC 3372)",
    type: "nebula",
    scaleTier: 2,
    location: "Carina",
    galaxy: "Milky Way",
    solarSystem: null,
    distanceFromEarthKm: 8.04e16,
    radiusKm: 2.8e14,
    colorHex: 0xff6699,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 7,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Hydrogen: 88, Dust: 12 },
    },
    description:
      "A colossal, bright diffuse nebula housing the unstable hypergiant star system Eta Carinae and the Mystic Mountain.",
    tags: ["nebula", "starburst", "eta carinae"],
  },
  {
    id: "crab-nebula",
    name: "Crab Nebula (Messier 1)",
    type: "nebula",
    scaleTier: 2,
    location: "Taurus",
    galaxy: "Milky Way",
    solarSystem: null,
    distanceFromEarthKm: 6.15e16,
    radiusKm: 5.2e13,
    colorHex: 0x4dd0e1,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 8,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { IonizedGas: 90, SynchrotronPlasma: 10 },
    },
    description:
      "The glowing expanding debris shell of a supernova witnessed by Earth astronomers in the year 1054 CE.",
    tags: ["nebula", "supernova remnant", "messier 1"],
  },
  {
    id: "horsehead-nebula",
    name: "Horsehead Nebula (Barnard 33)",
    type: "nebula",
    scaleTier: 2,
    location: "Orion",
    galaxy: "Milky Way",
    solarSystem: null,
    distanceFromEarthKm: 1.3e16,
    radiusKm: 1.6e13,
    colorHex: 0x8b3a3a,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 5,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { DarkDust: 70, MolecularHydrogen: 30 },
    },
    description: "A famous dark absorption nebula silhouetted majestically against glowing red ionized hydrogen gas.",
    tags: ["nebula", "dark nebula", "horsehead"],
  },
  {
    id: "ring-nebula",
    name: "Ring Nebula (Messier 57)",
    type: "nebula",
    scaleTier: 2,
    location: "Lyra",
    galaxy: "Milky Way",
    solarSystem: null,
    distanceFromEarthKm: 2.43e16,
    radiusKm: 9.5e12,
    colorHex: 0x26c6da,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 6,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { OxygenIII: 40, NitrogenII: 30, Hydrogen: 30 },
    },
    description: "A glowing planetary nebula smoke-ring shed by a dying central white dwarf star.",
    tags: ["nebula", "planetary nebula", "white dwarf"],
  },
  {
    id: "helix-nebula",
    name: "Helix Nebula (The Eye of God / NGC 7293)",
    type: "nebula",
    scaleTier: 2,
    location: "Aquarius",
    galaxy: "Milky Way",
    solarSystem: null,
    distanceFromEarthKm: 6.19e15,
    radiusKm: 1.4e13,
    colorHex: 0x00e5ff,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 5,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Oxygen: 45, Hydrogen: 45, Nitrogen: 10 },
    },
    description: "One of the closest and most vivid planetary nebulae to Earth, resembling a giant cosmic eye.",
    tags: ["nebula", "eye of god", "planetary nebula"],
  },
  {
    id: "tarantula-nebula",
    name: "Tarantula Nebula (30 Doradus)",
    type: "nebula",
    scaleTier: 2,
    location: "Large Magellanic Cloud",
    galaxy: "Large Magellanic Cloud",
    solarSystem: null,
    distanceFromEarthKm: 1.54e18,
    radiusKm: 9.5e14,
    colorHex: 0xff4081,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 8,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Hydrogen: 85, Helium: 12, HeavyMetals: 3 },
    },
    description: "The most luminous and active starburst nursery region in the entire Local Group of galaxies.",
    tags: ["nebula", "starburst", "lmc"],
  },

  // =========================================================================
  // SCALE 3: Galactic Scale & Local Group
  // =========================================================================
  {
    id: "milky-way",
    name: "The Milky Way",
    type: "galaxy",
    scaleTier: 3,
    location: "Local Group",
    galaxy: "Milky Way",
    solarSystem: null,
    distanceFromEarthKm: 0,
    radiusKm: 4.73e17,
    colorHex: 0xd9c9ff,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 0,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Trace: 100 },
    },
    description: "Our home barred spiral galaxy — 100 to 400 billion stars revolving around Sagittarius A*.",
    tags: ["galaxy", "home galaxy", "spiral"],
  },
  {
    id: "andromeda",
    name: "Andromeda Galaxy (M31)",
    type: "galaxy",
    scaleTier: 3,
    location: "Local Group",
    galaxy: "Local Group",
    solarSystem: null,
    distanceFromEarthKm: 2.365e19,
    radiusKm: 1.1e18,
    colorHex: 0xbcd4ff,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 0,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Trace: 100 },
    },
    description:
      "Our majestic neighboring spiral galaxy spanning one trillion stars, on collision course with the Milky Way in 4.5B years.",
    tags: ["galaxy", "local group", "spiral"],
  },
  {
    id: "triangulum",
    name: "Triangulum Galaxy (M33)",
    type: "galaxy",
    scaleTier: 3,
    location: "Local Group",
    galaxy: "Local Group",
    solarSystem: null,
    distanceFromEarthKm: 2.727e19,
    radiusKm: 3e17,
    colorHex: 0xc9e3ff,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 0,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Trace: 100 },
    },
    description: "The third-largest galaxy in our Local Group — a rich, pinwheel-like starburst spiral.",
    tags: ["galaxy", "local group", "pinwheel"],
  },
  {
    id: "large-magellanic-cloud",
    name: "Large Magellanic Cloud (LMC)",
    type: "galaxy",
    scaleTier: 3,
    location: "Milky Way Satellite",
    galaxy: "Local Group",
    solarSystem: null,
    distanceFromEarthKm: 1.54e18,
    radiusKm: 1.4e17,
    colorHex: 0xffab91,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 0,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Trace: 100 },
    },
    description: "A disrupted dwarf satellite galaxy orbiting the Milky Way, ablaze with active starburst regions.",
    tags: ["galaxy", "satellite galaxy", "dwarf galaxy"],
  },
  {
    id: "small-magellanic-cloud",
    name: "Small Magellanic Cloud (SMC)",
    type: "galaxy",
    scaleTier: 3,
    location: "Milky Way Satellite",
    galaxy: "Local Group",
    solarSystem: null,
    distanceFromEarthKm: 1.93e18,
    radiusKm: 7.0e16,
    colorHex: 0xffcc80,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 0,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Trace: 100 },
    },
    description: "A dwarf galaxy companion to the LMC containing several hundred million stars.",
    tags: ["galaxy", "satellite galaxy", "dwarf galaxy"],
  },
  {
    id: "sombrero-galaxy",
    name: "Sombrero Galaxy (Messier 104)",
    type: "galaxy",
    scaleTier: 3,
    location: "Virgo / Corvus",
    galaxy: "Virgo Cluster",
    solarSystem: null,
    distanceFromEarthKm: 2.77e20,
    radiusKm: 4.8e17,
    colorHex: 0xffe0b2,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 0,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Trace: 100 },
    },
    description:
      "An unbarred spiral galaxy featuring an exceptionally bright bulbous core and a prominent dark dust absorption rim.",
    tags: ["galaxy", "sombrero", "messier 104"],
  },
  {
    id: "whirlpool-galaxy",
    name: "Whirlpool Galaxy (Messier 51a)",
    type: "galaxy",
    scaleTier: 3,
    location: "Canes Venatici",
    galaxy: "M51 Group",
    solarSystem: null,
    distanceFromEarthKm: 2.18e20,
    radiusKm: 3.6e17,
    colorHex: 0x90caf9,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 0,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Trace: 100 },
    },
    description:
      "A classic grand-design spiral galaxy actively interacting and merging with its companion galaxy NGC 5195.",
    tags: ["galaxy", "grand design", "spiral", "messier 51"],
  },
  {
    id: "messier-87",
    name: "Messier 87 (Virgo A / M87*)",
    type: "galaxy",
    scaleTier: 3,
    location: "Virgo Cluster",
    galaxy: "Virgo Cluster",
    solarSystem: null,
    distanceFromEarthKm: 5.06e20,
    radiusKm: 1.2e18,
    colorHex: 0xffcc80,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 0,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Trace: 100 },
    },
    description:
      "A giant elliptical galaxy hosting the historic Event Horizon Telescope-imaged 6.5-billion-solar-mass black hole and a 5,000-ly relativistic plasma jet.",
    tags: ["galaxy", "elliptical", "m87", "supermassive black hole"],
  },
  {
    id: "centaurus-a",
    name: "Centaurus A (NGC 5128)",
    type: "galaxy",
    scaleTier: 3,
    location: "Centaurus",
    galaxy: "Centaurus A Group",
    solarSystem: null,
    distanceFromEarthKm: 1.23e20,
    radiusKm: 6.0e17,
    colorHex: 0xce93d8,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 0,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Trace: 100 },
    },
    description:
      "A dramatic active radio galaxy crossed by a dense warped dust lane and shooting massive plasma jets into intergalactic space.",
    tags: ["galaxy", "radio galaxy", "active galaxy"],
  },
  {
    id: "hoags-object",
    name: "Hoag's Object",
    type: "galaxy",
    scaleTier: 3,
    location: "Serpens Caput",
    galaxy: "Isolated",
    solarSystem: null,
    distanceFromEarthKm: 5.79e21,
    radiusKm: 5.7e17,
    colorHex: 0x80deea,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 0,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Trace: 100 },
    },
    description:
      "A rare, perfectly symmetrical ring galaxy with a luminous circle of young blue star clusters surrounding a golden nucleus.",
    tags: ["galaxy", "ring galaxy", "exotic galaxy"],
  },

  // =========================================================================
  // SCALE 4: Extragalactic, Quasars, Superclusters, Voids, & Universe Scaffolding
  // =========================================================================
  {
    id: "ton-618",
    name: "TON 618 (Hyperluminous Quasar)",
    type: "blackHole",
    scaleTier: 4,
    location: "Canes Venatici",
    galaxy: "TON 618",
    solarSystem: null,
    distanceFromEarthKm: 1.72e23,
    radiusKm: 1.95e11,
    colorHex: 0xff0055,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: Infinity,
      radiationIndex: 10,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Singularity: 100 },
    },
    description:
      "An ultra-massive black hole of 66 billion solar masses powering a hyperluminous quasar that shines brighter than 140 trillion suns.",
    tags: ["quasar", "black hole", "ultra-massive", "brightest object"],
  },
  {
    id: "quasar-3c273",
    name: "3C 273",
    type: "blackHole",
    scaleTier: 4,
    location: "Virgo",
    galaxy: "3C 273 Host",
    solarSystem: null,
    distanceFromEarthKm: 2.31e22,
    radiusKm: 2.6e9,
    colorHex: 0xffd700,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: Infinity,
      radiationIndex: 10,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Singularity: 100 },
    },
    description:
      "The first quasar ever identified in 1963, powered by a billion-solar-mass central engine shooting a 200,000-light-year plasma jet.",
    tags: ["quasar", "first quasar", "active galactic nucleus"],
  },
  {
    id: "virgo-cluster",
    name: "Virgo Galaxy Cluster",
    type: "structure",
    scaleTier: 4,
    location: "Virgo Supercluster Core",
    galaxy: "Virgo Supercluster",
    solarSystem: null,
    distanceFromEarthKm: 5.1e20,
    radiusKm: 7.1e19,
    colorHex: 0xffd54f,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 0,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Galaxies: 1300, DarkMatter: 80 },
    },
    description: "The colossal cluster of over 1,300 galaxies forming the heart of the Local Supercluster.",
    tags: ["galaxy cluster", "structure", "virgo"],
  },
  {
    id: "great-attractor",
    name: "The Great Attractor",
    type: "structure",
    scaleTier: 4,
    location: "Zone of Avoidance (Norma Cluster)",
    galaxy: "Laniakea",
    solarSystem: null,
    distanceFromEarthKm: 2.08e21,
    radiusKm: 3e20,
    colorHex: 0xff7043,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 0,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { GravitationalAnomaly: 100 },
    },
    description:
      "An immense gravitational anomaly pulling millions of galaxies across hundreds of millions of light-years toward its mysterious center.",
    tags: ["great attractor", "gravitational anomaly", "structure"],
  },
  {
    id: "bootes-void",
    name: "Boötes Void (The Great Nothing)",
    type: "structure",
    scaleTier: 4,
    location: "Boötes",
    galaxy: "Intergalactic Space",
    solarSystem: null,
    distanceFromEarthKm: 6.62e21,
    radiusKm: 1.56e21,
    colorHex: 0x37474f,
    orbit: null,
    environment: {
      surfaceTempC: -270.4,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 0,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { NearVacuum: 100 },
    },
    description:
      "A gigantic sphere of nearly empty space 330 million light-years across containing almost no galaxies.",
    tags: ["void", "the great nothing", "structure"],
  },
  {
    id: "laniakea",
    name: "Laniakea Supercluster",
    type: "structure",
    scaleTier: 4,
    location: "Local Supercluster",
    galaxy: "Laniakea",
    solarSystem: null,
    distanceFromEarthKm: 0,
    radiusKm: 4.7e21,
    colorHex: 0xffe9c2,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 0,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Trace: 100 },
    },
    description:
      'The vast supercluster of 100,000 galaxies that contains the Milky Way — "immense heaven" in Hawaiian.',
    tags: ["supercluster", "structure", "laniakea"],
  },
  {
    id: "cosmic-web",
    name: "The Cosmic Web",
    type: "structure",
    scaleTier: 4,
    location: "Observable Universe",
    galaxy: "Observable Universe",
    solarSystem: null,
    distanceFromEarthKm: 0,
    radiusKm: 4.4e23,
    colorHex: 0x9fd6ff,
    orbit: null,
    environment: {
      surfaceTempC: NaN,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 0,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { Trace: 100 },
    },
    description:
      "The immense filament-and-void scaffolding of dark matter along which every galaxy in existence is strung.",
    tags: ["cosmic web", "structure", "universe scaffolding"],
  },
  {
    id: "cmb-horizon",
    name: "Cosmic Microwave Background Horizon",
    type: "structure",
    scaleTier: 4,
    location: "Edge of the observable universe",
    galaxy: "Observable Universe",
    solarSystem: null,
    distanceFromEarthKm: 4.4e23,
    radiusKm: 0,
    colorHex: 0xffd7a8,
    orbit: null,
    environment: {
      surfaceTempC: -270.4,
      atmosphericPressureAtm: 0,
      surfaceGravityG: 0,
      radiationIndex: 0,
      hasLiquidWater: false,
      isGasGiant: false,
      composition: { PrimordialPhotons: 100 },
    },
    description:
      "The faint thermal afterglow of the Big Bang itself — the oldest and farthest light in the cosmos (13.8 billion years old).",
    tags: ["cmb", "big bang", "structure", "edge of universe"],
  },
];

/** @type {Map<string, CelestialBody>} */
const bodiesById = new Map(CELESTIAL_BODIES.map((b) => [b.id, b]));

/** @param {string} id @returns {?CelestialBody} */
export function getCelestialBodyById(id) {
  return bodiesById.get(id) ?? null;
}

/** @param {number} scaleTier @returns {CelestialBody[]} */
export function getBodiesByScale(scaleTier) {
  return CELESTIAL_BODIES.filter((b) => b.scaleTier === scaleTier);
}

/**
 * Case-insensitive substring/tag search across the database.
 * @param {string} query
 * @param {CelestialBody[]} [source]
 * @returns {CelestialBody[]} matches, best (name-match) first.
 */
export function searchCelestialBodies(query, source = CELESTIAL_BODIES) {
  const q = String(query ?? "")
    .trim()
    .toLowerCase();
  if (!q) return [];
  const nameMatches = [];
  const otherMatches = [];
  for (const body of source) {
    const name = body.name.toLowerCase();
    if (name.includes(q)) {
      nameMatches.push(body);
    } else if (body.tags.some((t) => t.toLowerCase().includes(q)) || body.location.toLowerCase().includes(q)) {
      otherMatches.push(body);
    }
  }
  nameMatches.sort((a, b) => a.name.length - b.name.length);
  return [...nameMatches, ...otherMatches];
}

const REQUIRED_FIELDS = [
  "id",
  "name",
  "type",
  "scaleTier",
  "location",
  "galaxy",
  "solarSystem",
  "distanceFromEarthKm",
  "radiusKm",
  "colorHex",
  "orbit",
  "environment",
  "description",
  "tags",
];
const REQUIRED_ENV_FIELDS = [
  "surfaceTempC",
  "atmosphericPressureAtm",
  "surfaceGravityG",
  "radiationIndex",
  "hasLiquidWater",
  "isGasGiant",
  "composition",
];

/**
 * Validates the whole database for required fields and sane numeric bounds.
 * Used by data-integrity tests, and defensively by the app on boot.
 * @param {CelestialBody[]} [bodies]
 * @returns {{valid: boolean, errors: string[]}}
 */
export function validateCelestialData(bodies = CELESTIAL_BODIES) {
  const errors = [];
  const seenIds = new Set();

  if (!Array.isArray(bodies) || bodies.length === 0) {
    return { valid: false, errors: ["Celestial database is empty"] };
  }

  for (const body of bodies) {
    const label = body?.id ?? "(missing id)";
    for (const field of REQUIRED_FIELDS) {
      if (!(field in (body ?? {}))) errors.push(`${label}: missing field "${field}"`);
    }
    if (body?.id) {
      if (seenIds.has(body.id)) errors.push(`${label}: duplicate id`);
      seenIds.add(body.id);
    }
    if (typeof body?.scaleTier !== "number" || body.scaleTier < 0 || body.scaleTier > 4) {
      errors.push(`${label}: scaleTier out of range [0,4]`);
    }
    if (typeof body?.distanceFromEarthKm !== "number" || body.distanceFromEarthKm < 0) {
      errors.push(`${label}: distanceFromEarthKm must be >= 0`);
    }
    if (typeof body?.radiusKm !== "number" || body.radiusKm < 0) {
      errors.push(`${label}: radiusKm must be >= 0`);
    }
    if (body?.orbit) {
      if (typeof body.orbit.semiMajorAxisAu !== "number")
        errors.push(`${label}: orbit.semiMajorAxisAu must be a number`);
      if (typeof body.orbit.periodDays !== "number" || body.orbit.periodDays <= 0) {
        errors.push(`${label}: orbit.periodDays must be > 0`);
      }
    }
    const env = body?.environment;
    if (!env) {
      errors.push(`${label}: missing environment`);
    } else {
      for (const field of REQUIRED_ENV_FIELDS) {
        if (!(field in env)) errors.push(`${label}: environment missing "${field}"`);
      }
    }
    if (!Array.isArray(body?.tags)) errors.push(`${label}: tags must be an array`);
  }

  return { valid: errors.length === 0, errors };
}
